### ISSUE TITLE
Log al reproduccir

### ISSUE THREAD

**Issue by maasencioh** [VoicePiCar/AndroidRecorder#4]
AL reproducir saca el error `E/MediaPlayer: Should have subtitle controller already set`, pero la aplicación sigue funcionando normalmente

**Comment by anmrdz** [comment]
Como tal no es un error de la aplicación. Mas información: http://stackoverflow.com/questions/20087804/should-have-subtitle-controller-already-set-mediaplayer-error-android

**Comment by maasencioh** [comment]
Era más una anotación para buscarla, pero gracias 😃

**Comment by anmrdz** [comment]
> Hola, si pudieran leer mi mensaje. Estoy tratando de compilar esta app, pero no lo consigo. Me gustaría comunicarme alguno de ustedes a ver si pueden ayudarme please! 

Hola Victor,

Nos podrías comentar que problema tienes? Si puedes adjuntar screenshots y/o logs mucho mejor, también coméntanos que versión del sdk estas usando?

**Comment by Victor-Venegas-M** [comment]
![Screenshot_4](https://github.com/VoicePiCar/AndroidRecorder/assets/101227409/61bc664c-d25d-497f-b783-71b1adcf58e3)
![Screenshot_3](https://github.com/VoicePiCar/AndroidRecorder/assets/101227409/450bd739-9198-4da9-be33-350c1475039f)
![Screenshot_2](https://github.com/VoicePiCar/AndroidRecorder/assets/101227409/674f6410-fcf1-431a-9c72-172f97668592)
![Screenshot_1](https://github.com/VoicePiCar/AndroidRecorder/assets/101227409/4cd90317-dde1-4359-bd34-9556b33887e0)

Tengo estas capturas.
venegas.victorm@gmail.com ese es mi correo por si podemos comunicarnos please!
